![WhatsApp Image 2024-07-09 at 9.24.05 AM.jpeg](attachment:7619c5ca-a714-42ed-93bc-946fb02e1aea.jpeg)

In [88]:
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport
import warnings 
warnings.filterwarnings("ignore")


In [89]:
"titanic_train.csv"


'titanic_train.csv'

In [90]:
titanic_data = pd.read_csv("titanic_train.csv")

In [91]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [92]:
titanic_data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [93]:
report = ProfileReport(titanic_data)
report.to_file("TodaysReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [94]:
titanic_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [95]:
titanic_data.columns = ['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked']

In [96]:
titanic_data

passengerId  survived  pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  name     sex   age  sibsp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     parch            ticket     fare cabin embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [97]:
titanic_data.dtypes

passengerId      int64
survived         int64
pclass           int64
name            object
sex             object
age            float64
sibsp            int64
parch            int64
ticket          object
fare           float64
cabin           object
embarked        object
dtype: object

In [98]:
titanic_data['pclass'].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [99]:
titanic_data = titanic_data.astype({"pclass":"object"})

In [100]:
titanic_data.dtypes

passengerId      int64
survived         int64
pclass          object
name            object
sex             object
age            float64
sibsp            int64
parch            int64
ticket          object
fare           float64
cabin           object
embarked        object
dtype: object

In [101]:
titanic_data["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [102]:
titanic_data = titanic_data.astype({"survived":"int"})

In [103]:
titanic_data.dtypes

passengerId      int64
survived         int32
pclass          object
name            object
sex             object
age            float64
sibsp            int64
parch            int64
ticket          object
fare           float64
cabin           object
embarked        object
dtype: object

In [104]:
titanic_data.isna().sum()

passengerId      0
survived         0
pclass           0
name             0
sex              0
age            177
sibsp            0
parch            0
ticket           0
fare             0
cabin          687
embarked         2
dtype: int64

In [105]:
md = titanic_data["age"].median()

In [106]:
print(md)

28.0


In [107]:
titanic_data["age"] = titanic_data["age"].fillna(md) 

In [108]:
titanic_data.isna().sum()


passengerId      0
survived         0
pclass           0
name             0
sex              0
age              0
sibsp            0
parch            0
ticket           0
fare             0
cabin          687
embarked         2
dtype: int64

In [109]:
titanic_data["cabin"].value_counts()

cabin
B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: count, Length: 147, dtype: int64

In [110]:
titanic_data.shape

(891, 12)

In [111]:
891 - 687 # subtracting Isnull cabin value - total number of values in cabin 

204

In [112]:
titanic_data.drop(["cabin","passengerId"],axis=1,inplace=True)

In [113]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int32  
 1   pclass    891 non-null    object 
 2   name      891 non-null    object 
 3   sex       891 non-null    object 
 4   age       891 non-null    float64
 5   sibsp     891 non-null    int64  
 6   parch     891 non-null    int64  
 7   ticket    891 non-null    object 
 8   fare      891 non-null    float64
 9   embarked  889 non-null    object 
dtypes: float64(2), int32(1), int64(2), object(5)
memory usage: 66.3+ KB


In [114]:
titanic_data["embarked"].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [115]:
mode_v1 = titanic_data["embarked"][0]
print(f"Most busy Port is = {mode_v1}")

Most busy Port is = S


In [116]:
titanic_data["embarked"] = titanic_data["embarked"].fillna(mode_v1)

In [117]:
titanic_data.isna().sum()

survived    0
pclass      0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
embarked    0
dtype: int64

In [118]:
titanic_data["familysize"] = titanic_data["sibsp"] + titanic_data["parch"] + 1

In [119]:
titanic_data.head(10)

survived pclass                                               name     sex  \
0         0      3                            Braund, Mr. Owen Harris    male   
1         1      1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2         1      3                             Heikkinen, Miss. Laina  female   
3         1      1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4         0      3                           Allen, Mr. William Henry    male   
5         0      3                                   Moran, Mr. James    male   
6         0      1                            McCarthy, Mr. Timothy J    male   
7         0      3                     Palsson, Master. Gosta Leonard    male   
8         1      3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   
9         1      2                Nasser, Mrs. Nicholas (Adele Achem)  female   

    age  sibsp  parch            ticket     fare embarked  familysize  
0  22.0      1      0         A/5 21171   7.2500        S           2  
1  38.0      1      0          PC 17599  71.2833        C           2  
2  26.0      0      0  STON/O2. 3101282   7.9250        S           1  
3  35.0      1      0            113803  53.1000        S           2  
4  35.0      0      0            373450   8.0500        S           1  
5  28.0      0      0            330877   8.4583        Q           1  
6  54.0      0      0             17463  51.8625        S           1  
7   2.0      3      1            349909  21.0750        S           5  
8  27.0      0      2            347742  11.1333        S           3  
9  14.0      1      0            237736  30.0708        C           2

In [120]:
titanic_data.drop(["sibsp","parch"],axis=1,inplace=True)

In [121]:
titanic_data.head(10)

survived pclass                                               name     sex  \
0         0      3                            Braund, Mr. Owen Harris    male   
1         1      1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2         1      3                             Heikkinen, Miss. Laina  female   
3         1      1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4         0      3                           Allen, Mr. William Henry    male   
5         0      3                                   Moran, Mr. James    male   
6         0      1                            McCarthy, Mr. Timothy J    male   
7         0      3                     Palsson, Master. Gosta Leonard    male   
8         1      3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   
9         1      2                Nasser, Mrs. Nicholas (Adele Achem)  female   

    age            ticket     fare embarked  familysize  
0  22.0         A/5 21171   7.2500        S           2  
1  38.0          PC 17599  71.2833        C           2  
2  26.0  STON/O2. 3101282   7.9250        S           1  
3  35.0            113803  53.1000        S           2  
4  35.0            373450   8.0500        S           1  
5  28.0            330877   8.4583        Q           1  
6  54.0             17463  51.8625        S           1  
7   2.0            349909  21.0750        S           5  
8  27.0            347742  11.1333        S           3  
9  14.0            237736  30.0708        C           2

In [122]:
titanic_data.columns

Index(['survived', 'pclass', 'name', 'sex', 'age', 'ticket', 'fare',
       'embarked', 'familysize'],
      dtype='object')

In [123]:
x = titanic_data.drop(["survived","name","ticket"],axis = 1)
x

pclass     sex   age     fare embarked  familysize
0        3    male  22.0   7.2500        S           2
1        1  female  38.0  71.2833        C           2
2        3  female  26.0   7.9250        S           1
3        1  female  35.0  53.1000        S           2
4        3    male  35.0   8.0500        S           1
..     ...     ...   ...      ...      ...         ...
886      2    male  27.0  13.0000        S           1
887      1  female  19.0  30.0000        S           1
888      3  female  28.0  23.4500        S           4
889      1    male  26.0  30.0000        C           1
890      3    male  32.0   7.7500        Q           1

[891 rows x 6 columns]

In [124]:
dummy = pd.get_dummies(x,drop_first=True,dtype = int)
dummy

age     fare  familysize  pclass_2  pclass_3  sex_male  embarked_Q  \
0    22.0   7.2500           2         0         1         1           0   
1    38.0  71.2833           2         0         0         0           0   
2    26.0   7.9250           1         0         1         0           0   
3    35.0  53.1000           2         0         0         0           0   
4    35.0   8.0500           1         0         1         1           0   
..    ...      ...         ...       ...       ...       ...         ...   
886  27.0  13.0000           1         1         0         1           0   
887  19.0  30.0000           1         0         0         0           0   
888  28.0  23.4500           4         0         1         0           0   
889  26.0  30.0000           1         0         0         1           0   
890  32.0   7.7500           1         0         1         1           1   

     embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 8 columns]

In [246]:
y = titanic_data["survived"].map({0:"Not Survived",1:"Survived"})
y

0      Not Survived
1          Survived
2          Survived
3          Survived
4      Not Survived
           ...     
886    Not Survived
887        Survived
888    Not Survived
889        Survived
890    Not Survived
Name: survived, Length: 891, dtype: object

In [217]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(dummy,y,test_size = 0.2 , random_state = 500 , shuffle = True)
print(f"x_train is {x_train.shape}")
print(f"x_test is {x_test.shape}")
print(f"y_train is {y_train.shape}")
print(f"y_test is {y_test.shape}")

x_train is (712, 8)
x_test is (179, 8)
y_train is (712,)
y_test is (179,)


In [219]:
from sklearn.linear_model import LogisticRegression

In [221]:
model_logr = LogisticRegression()
model_logr

LogisticRegression()

In [223]:
model_logr.fit(x_train,y_train)

LogisticRegression()

In [225]:
y_pred = model_logr.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1])

In [227]:
model_logr.predict([[56, 509900, 3, 1, 0, 0, 0, 0]])

array([1])

In [244]:
model_logr.predict([[36, 5, 1, 1, 1, 0, 0, 0]])

array([0])

In [229]:
from sklearn.metrics import classification_report

In [231]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       108
           1       0.71      0.72      0.71        71

    accuracy                           0.77       179
   macro avg       0.76      0.76      0.76       179
weighted avg       0.77      0.77      0.77       179



In [233]:
from sklearn.metrics import accuracy_score

In [235]:
accuracy_score(y_test,y_pred)

0.770949720670391

In [240]:
from sklearn.metrics import confusion_matrix

In [242]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[87, 21],
       [20, 51]], dtype=int64)

In [252]:
import joblib
joblib.dump(model_logr,open("titanic_model.pkl","wb"))